### ISSUE TITLE
Solution doesn't run 

### ISSUE THREAD

**Issue by GFoley83** [aboelkassem/temporal-demo#1]
There's no host available for localhost:7233

```cs
System.InvalidOperationException: Connection failed: Server connection error: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." })))
   at Temporalio.Bridge.Client.ConnectAsync(Runtime runtime, TemporalConnectionOptions options)
   at Temporalio.Client.TemporalConnection.ConnectAsync(TemporalConnectionOptions options)
   at Temporalio.Client.TemporalClient.ConnectAsync(TemporalClientConnectOptions options)
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in C:\dev\temporal-demo\TemporalDemo.Web\Program.cs:line 24
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteTaskOfString>g__ExecuteAwaited|59_0(Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by GFoley83** [comment]
Never mind. Looks like you have to run a seperate local dev cluster:
https://docs.temporal.io/dev-guide/typescript/foundations#run-a-development-server
